# Generated by Django 5.2 on 2025-06-13 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('ID_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=50)),
                ('descripcion_categoria', models.TextField(blank=True, null=True)),
                ('capacidad_categoria', models.IntegerField()),
                ('imagen_categoria', models.ImageField(blank=True, null=True, upload_to='imagenes_categorias/')),
            ],
            options={
                'verbose_name': 'Categorías',
                'verbose_name_plural': 'Categorías',
                'db_table': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Direccion',
                'verbose_name_plural': 'Direcciones',
                'db_table': 'Direcciones',
            },
        ),
        migrations.CreateModel(
            name='Estados_Reservas',
            fields=[
                ('ID_estado_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_estado_reserva', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Estado de Reserva',
                'verbose_name_plural': 'Estados de Reservas',
                'db_table': 'Estados_Reservas',
            },
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Localidad',
                'verbose_name_plural': 'Localidades',
                'db_table': 'Localidades',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
                'db_table': 'Países',
            },
        ),
        migrations.CreateModel(
            name='Servicios_Hoteles',
            fields=[
                ('ID_servicio_hotel', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_servicio', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Servicio Hotel',
                'verbose_name_plural': 'Servicios Hoteles',
                'db_table': 'Servicios_Hoteles',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('ID_hotel', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_hotel', models.CharField(max_length=100)),
                ('descripcion_hotel', models.TextField(blank=True, null=True)),
                ('cantidad_estrellas_hotel', models.IntegerField()),
                ('imagen_hotel', models.ImageField(blank=True, null=True, upload_to='imagenes_hoteles/')),
                ('ID_direccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.direccion')),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hoteles',
                'db_table': 'Hoteles',
            },
        ),
        migrations.AddField(
            model_name='direccion',
            name='localidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.localidad'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.pais'),
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.pais')),
            ],
            options={
                'db_table': 'Provincias',
            },
        ),
        migrations.AddField(
            model_name='localidad',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.provincia'),
        ),
        migrations.CreateModel(
            name='Reservas_Hoteles',
            fields=[
                ('ID_reserva_hotel', models.AutoField(primary_key=True, serialize=False)),
                ('monto_total_hotel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_reserva', models.DateField(auto_now_add=True)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_egreso', models.DateField()),
                ('ID_estado_reserva', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.estados_reservas')),
            ],
            options={
                'verbose_name': 'Reserva Hotel',
                'verbose_name_plural': 'Reservas Hoteles',
                'db_table': 'Reservas_Hoteles',
            },
        ),
        migrations.CreateModel(
            name='Reservas_Hoteles_Detalles',
            fields=[
                ('ID_reserva_hotel_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_habitaciones', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ID_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.categorias')),
                ('ID_reserva_hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.reservas_hoteles')),
            ],
            options={
                'verbose_name': 'Detalle Reserva Hotel',
                'verbose_name_plural': 'Detalles Reservas Hoteles',
                'db_table': 'Reservas_Hoteles_Detalles',
            },
        ),
        migrations.CreateModel(
            name='Servicios_Categorias_Habitaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.categorias')),
                ('ID_servicio_hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.servicios_hoteles')),
            ],
            options={
                'verbose_name': 'Servicio por Categoría de Habitación',
                'verbose_name_plural': 'Servicios por Categorías de Habitaciones',
                'db_table': 'Servicios_Categorias_Habitaciones',
                'unique_together': {('ID_servicio_hotel', 'ID_categoria')},
            },
        ),
        migrations.CreateModel(
            name='Viajeros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('fecha_nacimiento', models.DateField()),
                ('clave', models.CharField(max_length=128)),
                ('ID_direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.direccion')),
            ],
            options={
                'verbose_name': 'Viajero',
                'verbose_name_plural': 'Viajeros',
                'db_table': 'Viajeros',
            },
        ),
        migrations.AddField(
            model_name='reservas_hoteles',
            name='ID_viajero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.viajeros'),
        ),
        migrations.CreateModel(
            name='Disponibilidad_Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cantidad_disponible', models.PositiveIntegerField()),
                ('ID_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.categorias')),
                ('ID_hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel')),
            ],
            options={
                'verbose_name': 'Disponibilidad_Categorias',
                'verbose_name_plural': 'Disponibilidad_Categorias',
                'db_table': 'Disponibilidad_Categorias',
                'unique_together': {('ID_hotel', 'ID_categoria', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='Hoteles_Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.categorias')),
                ('ID_hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel')),
            ],
            options={
                'verbose_name': 'Hoteles_Categorias',
                'verbose_name_plural': 'Hoteles_Categorias',
                'db_table': 'Hoteles_Categorias',
                'unique_together': {('ID_hotel', 'ID_categoria')},
            },
        ),
        migrations.CreateModel(
            name='Hoteles_Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel')),
                ('ID_servicio_hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.servicios_hoteles')),
            ],
            options={
                'verbose_name': 'Hoteles_Servicios',
                'verbose_name_plural': 'Hoteles_Servicios',
                'db_table': 'Hoteles_Servicios',
                'unique_together': {('ID_hotel', 'ID_servicio_hotel')},
            },
        ),
        migrations.CreateModel(
            name='Categorias_Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.servicios_categorias_habitaciones')),
                ('ID_servicio_hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.servicios_hoteles')),
            ],
            options={
                'verbose_name': 'Categoría Servicio',
                'verbose_name_plural': 'Categorías Servicios',
                'db_table': 'Categorias_Servicios',
                'unique_together': {('ID_servicio_hotel', 'ID_categoria')},
            },
        ),
    ]
