# Generated by Django 5.2 on 2025-05-19 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('capacidad', models.PositiveIntegerField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='categorias/')),
                ('precio', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=10)),
                ('cod_postal', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Dirección',
                'verbose_name_plural': 'Direcciones',
            },
        ),
        migrations.CreateModel(
            name='EstadoReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Estado Reserva',
                'verbose_name_plural': 'Estados Reservas',
            },
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Localidad',
                'verbose_name_plural': 'Localidades',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
            },
        ),
        migrations.CreateModel(
            name='ServicioCategoriaHabitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Servicio Categoría Habitación',
                'verbose_name_plural': 'Servicios Categorías Habitaciones',
            },
        ),
        migrations.CreateModel(
            name='ServicioHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Servicio Hotel',
                'verbose_name_plural': 'Servicios Hoteles',
            },
        ),
        migrations.CreateModel(
            name='DisponibilidadCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('capacidad_disponible', models.PositiveIntegerField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='hotel.categoria')),
            ],
            options={
                'verbose_name': 'Disponibilidad Categoría',
                'verbose_name_plural': 'Disponibilidad Categorías',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('estrellas', models.PositiveSmallIntegerField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='hoteles/')),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.direccion')),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hoteles',
            },
        ),
        migrations.AddField(
            model_name='direccion',
            name='localidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='hotel.localidad'),
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provincias', to='hotel.pais')),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
            },
        ),
        migrations.AddField(
            model_name='localidad',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localidades', to='hotel.provincia'),
        ),
        migrations.CreateModel(
            name='ReservaHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_reserva', models.DateField()),
                ('fecha_ingreso', models.DateField()),
                ('fecha_egreso', models.DateField()),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.estadoreserva')),
            ],
            options={
                'verbose_name': 'Reserva Hotel',
                'verbose_name_plural': 'Reservas Hoteles',
            },
        ),
        migrations.CreateModel(
            name='ReservaHotelDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_habitaciones', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sub_total', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.categoria')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.reservahotel')),
            ],
            options={
                'verbose_name': 'Reserva Hotel Detalle',
                'verbose_name_plural': 'Reservas Hoteles Detalles',
            },
        ),
        migrations.CreateModel(
            name='Viajero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('fecha_nacimiento', models.DateField()),
                ('clave', models.CharField(max_length=128)),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.direccion')),
            ],
            options={
                'verbose_name': 'Viajero',
                'verbose_name_plural': 'Viajeros',
            },
        ),
        migrations.AddField(
            model_name='reservahotel',
            name='viajero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.viajero'),
        ),
        migrations.CreateModel(
            name='HotelCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.categoria')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_hotel', to='hotel.hotel')),
            ],
            options={
                'verbose_name': 'Hotel Categoría',
                'verbose_name_plural': 'Hoteles Categorías',
                'unique_together': {('hotel', 'categoria')},
            },
        ),
        migrations.CreateModel(
            name='CategoriaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.categoria')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.serviciocategoriahabitacion')),
            ],
            options={
                'verbose_name': 'Categoría Servicio',
                'verbose_name_plural': 'Categorías Servicio',
                'unique_together': {('categoria', 'servicio')},
            },
        ),
        migrations.CreateModel(
            name='HotelServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.serviciohotel')),
            ],
            options={
                'verbose_name': 'Hotel Servicio',
                'verbose_name_plural': 'Hoteles Servicios',
                'unique_together': {('hotel', 'servicio')},
            },
        ),
    ]
