# Generated by Django 5.2 on 2025-04-27 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=100)),
                ('descripcion_categoria', models.TextField(blank=True, max_length=500)),
                ('capacidad_huesped', models.IntegerField()),
                ('cantidad_hab', models.IntegerField()),
                ('imagen_categoria', models.ImageField(blank=True, upload_to='habitaciones/%Y/%m/%d')),
                ('precio_base_categoria', models.DecimalField(decimal_places=2, max_digits=20)),
                ('estado_categoria', models.BooleanField(default=True)),
            ],
        ),
    ]
