# Generated by Django 5.2 on 2025-04-28 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nombre_categoria']},
        ),
        migrations.AlterModelOptions(
            name='servicio',
            options={'ordering': ['-nombre_servicio']},
        ),
        migrations.CreateModel(
            name='CategoriaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.categoria')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.servicio')),
            ],
            options={
                'unique_together': {('categoria', 'servicio')},
            },
        ),
    ]
