# Generated by Django 5.2 on 2025-04-28 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_alter_categoria_options_alter_servicio_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoHabitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_estado_habitacion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Estado de Habitación',
                'verbose_name_plural': 'Estados de Habitaciones',
                'ordering': ['descripcion_estado_habitacion'],
            },
        ),
    ]
