# Generated by Django 5.2 on 2025-04-28 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_estadohabitacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_estado_reserva', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Estado de Reserva',
                'verbose_name_plural': 'Estados de Reservas',
            },
        ),
    ]
