# Generated by Django 5.2 on 2025-04-28 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_estadoreserva'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_servicio', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Servicio de Hotel',
                'verbose_name_plural': 'Servicios de Hotel',
                'ordering': ['nombre_servicio'],
            },
        ),
    ]
