# Generated by Django 5.2 on 2025-04-28 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_domicilio_localidad_pais_hotel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotel',
            options={'verbose_name': 'Hotel', 'verbose_name_plural': 'Hoteles'},
        ),
        migrations.AlterModelOptions(
            name='localidad',
            options={'verbose_name': 'Localidad', 'verbose_name_plural': 'Localidades'},
        ),
        migrations.AlterModelOptions(
            name='pais',
            options={'verbose_name': 'País', 'verbose_name_plural': 'Países'},
        ),
    ]
