# Generated by Django 5.2 on 2025-04-28 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0010_reservahabitacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_habitacion', models.IntegerField()),
                ('monto_total_hotel', models.DecimalField(decimal_places=2, max_digits=20)),
                ('id_viajero', models.IntegerField()),
                ('id_hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_hoteles', to='hotel.hotel')),
            ],
            options={
                'verbose_name': 'Reserva de Hotel',
                'verbose_name_plural': 'Reservas de Hoteles',
            },
        ),
    ]
