# Generated by Django 5.2 on 2025-04-28 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_serviciohotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle_domicilio', models.CharField(max_length=100)),
                ('numero_domicilio', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_localidad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_pais', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_hotel', models.CharField(max_length=100)),
                ('descripcion_hotel', models.TextField()),
                ('cantidad_estrellas_hotel', models.IntegerField()),
                ('imagen_hotel', models.ImageField(blank=True, null=True, upload_to='imagenes_hoteles/')),
                ('id_domicilio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hotel', to='hotel.domicilio')),
            ],
        ),
        migrations.AddField(
            model_name='domicilio',
            name='id_localidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domicilios', to='hotel.localidad'),
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_provincia', models.CharField(max_length=100)),
                ('id_pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provincias', to='hotel.pais')),
            ],
        ),
        migrations.AddField(
            model_name='localidad',
            name='id_provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localidades', to='hotel.provincia'),
        ),
    ]
